//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 04:03:14 PM EDT 
//


package com.metlife.gpm.services.partydata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.metlife.gpm.services.partydata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PartyLogical_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyLogical");
    private final static QName _Party_QNAME = new QName("services.gpm.metlife.com/PartyData", "Party");
    private final static QName _ConsumerId_QNAME = new QName("services.gpm.metlife.com/PartyData", "ConsumerId");
    private final static QName _PartyRelationship_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyRelationship");
    private final static QName _PartyRestriction_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyRestriction");
    private final static QName _PartySearchCriteria_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartySearchCriteria");
    private final static QName _PartyGroup_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyGroup");
    private final static QName _Agreement_QNAME = new QName("services.gpm.metlife.com/PartyData", "Agreement");
    private final static QName _Address_QNAME = new QName("services.gpm.metlife.com/PartyData", "Address");
    private final static QName _BusinessFault_QNAME = new QName("services.gpm.metlife.com/PartyData", "BusinessFault");
    private final static QName _Information_QNAME = new QName("services.gpm.metlife.com/PartyData", "Information");
    private final static QName _PartyRelInAgreement_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyRelInAgreement");
    private final static QName _Group_QNAME = new QName("services.gpm.metlife.com/PartyData", "Group");
    private final static QName _PartyAlternateIdentifier_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyAlternateIdentifier");
    private final static QName _PartyAlternateName_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyAlternateName");
    private final static QName _OrganizationDetail_QNAME = new QName("services.gpm.metlife.com/PartyData", "OrganizationDetail");
    private final static QName _AgreementKey_QNAME = new QName("services.gpm.metlife.com/PartyData", "AgreementKey");
    private final static QName _PartyPhone_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyPhone");
    private final static QName _PartyCore_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyCore");
    private final static QName _PartyPreference_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyPreference");
    private final static QName _AgreementRelationship_QNAME = new QName("services.gpm.metlife.com/PartyData", "AgreementRelationship");
    private final static QName _AbstractFault_QNAME = new QName("services.gpm.metlife.com/PartyData", "AbstractFault");
    private final static QName _PartyRoleInAgreement_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyRoleInAgreement");
    private final static QName _PartyAddress_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyAddress");
    private final static QName _PersonDetail_QNAME = new QName("services.gpm.metlife.com/PartyData", "PersonDetail");
    private final static QName _PartyCitizenship_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyCitizenship");
    private final static QName _PartyElectronicAddress_QNAME = new QName("services.gpm.metlife.com/PartyData", "PartyElectronicAddress");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.metlife.gpm.services.partydata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PartyRoleInAgreement }
     * 
     */
    public PartyRoleInAgreement createPartyRoleInAgreement() {
        return new PartyRoleInAgreement();
    }

    /**
     * Create an instance of {@link AbstractFault }
     * 
     */
    public AbstractFault createAbstractFault() {
        return new AbstractFault();
    }

    /**
     * Create an instance of {@link AgreementRelationship }
     * 
     */
    public AgreementRelationship createAgreementRelationship() {
        return new AgreementRelationship();
    }

    /**
     * Create an instance of {@link PartyPreference }
     * 
     */
    public PartyPreference createPartyPreference() {
        return new PartyPreference();
    }

    /**
     * Create an instance of {@link PartyCore }
     * 
     */
    public PartyCore createPartyCore() {
        return new PartyCore();
    }

    /**
     * Create an instance of {@link PartyPhone }
     * 
     */
    public PartyPhone createPartyPhone() {
        return new PartyPhone();
    }

    /**
     * Create an instance of {@link AgreementKey }
     * 
     */
    public AgreementKey createAgreementKey() {
        return new AgreementKey();
    }

    /**
     * Create an instance of {@link OrganizationDetail }
     * 
     */
    public OrganizationDetail createOrganizationDetail() {
        return new OrganizationDetail();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link PartyAlternateName }
     * 
     */
    public PartyAlternateName createPartyAlternateName() {
        return new PartyAlternateName();
    }

    /**
     * Create an instance of {@link PartyAlternateIdentifier }
     * 
     */
    public PartyAlternateIdentifier createPartyAlternateIdentifier() {
        return new PartyAlternateIdentifier();
    }

    /**
     * Create an instance of {@link PartyElectronicAddress }
     * 
     */
    public PartyElectronicAddress createPartyElectronicAddress() {
        return new PartyElectronicAddress();
    }

    /**
     * Create an instance of {@link PartyCitizenship }
     * 
     */
    public PartyCitizenship createPartyCitizenship() {
        return new PartyCitizenship();
    }

    /**
     * Create an instance of {@link PartyAddress }
     * 
     */
    public PartyAddress createPartyAddress() {
        return new PartyAddress();
    }

    /**
     * Create an instance of {@link PersonDetail }
     * 
     */
    public PersonDetail createPersonDetail() {
        return new PersonDetail();
    }

    /**
     * Create an instance of {@link PartyRestriction }
     * 
     */
    public PartyRestriction createPartyRestriction() {
        return new PartyRestriction();
    }

    /**
     * Create an instance of {@link PartyRelationship }
     * 
     */
    public PartyRelationship createPartyRelationship() {
        return new PartyRelationship();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link PartyLogical }
     * 
     */
    public PartyLogical createPartyLogical() {
        return new PartyLogical();
    }

    /**
     * Create an instance of {@link Information }
     * 
     */
    public Information createInformation() {
        return new Information();
    }

    /**
     * Create an instance of {@link PartyRelInAgreement }
     * 
     */
    public PartyRelInAgreement createPartyRelInAgreement() {
        return new PartyRelInAgreement();
    }

    /**
     * Create an instance of {@link BusinessFault }
     * 
     */
    public BusinessFault createBusinessFault() {
        return new BusinessFault();
    }

    /**
     * Create an instance of {@link Agreement }
     * 
     */
    public Agreement createAgreement() {
        return new Agreement();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link PartyGroup }
     * 
     */
    public PartyGroup createPartyGroup() {
        return new PartyGroup();
    }

    /**
     * Create an instance of {@link PartySearchCriteria }
     * 
     */
    public PartySearchCriteria createPartySearchCriteria() {
        return new PartySearchCriteria();
    }

    /**
     * Create an instance of {@link ConsumerId }
     * 
     */
    public ConsumerId createConsumerId() {
        return new ConsumerId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyLogical }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyLogical")
    public JAXBElement<PartyLogical> createPartyLogical(PartyLogical value) {
        return new JAXBElement<PartyLogical>(_PartyLogical_QNAME, PartyLogical.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Party }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "Party")
    public JAXBElement<Party> createParty(Party value) {
        return new JAXBElement<Party>(_Party_QNAME, Party.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "ConsumerId")
    public JAXBElement<Object> createConsumerId(Object value) {
        return new JAXBElement<Object>(_ConsumerId_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyRelationship")
    public JAXBElement<PartyRelationship> createPartyRelationship(PartyRelationship value) {
        return new JAXBElement<PartyRelationship>(_PartyRelationship_QNAME, PartyRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyRestriction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyRestriction")
    public JAXBElement<PartyRestriction> createPartyRestriction(PartyRestriction value) {
        return new JAXBElement<PartyRestriction>(_PartyRestriction_QNAME, PartyRestriction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartySearchCriteria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartySearchCriteria")
    public JAXBElement<PartySearchCriteria> createPartySearchCriteria(PartySearchCriteria value) {
        return new JAXBElement<PartySearchCriteria>(_PartySearchCriteria_QNAME, PartySearchCriteria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyGroup")
    public JAXBElement<PartyGroup> createPartyGroup(PartyGroup value) {
        return new JAXBElement<PartyGroup>(_PartyGroup_QNAME, PartyGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Agreement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "Agreement")
    public JAXBElement<Agreement> createAgreement(Agreement value) {
        return new JAXBElement<Agreement>(_Agreement_QNAME, Agreement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "Address")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "BusinessFault")
    public JAXBElement<BusinessFault> createBusinessFault(BusinessFault value) {
        return new JAXBElement<BusinessFault>(_BusinessFault_QNAME, BusinessFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Information }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "Information")
    public JAXBElement<Information> createInformation(Information value) {
        return new JAXBElement<Information>(_Information_QNAME, Information.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyRelInAgreement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyRelInAgreement")
    public JAXBElement<PartyRelInAgreement> createPartyRelInAgreement(PartyRelInAgreement value) {
        return new JAXBElement<PartyRelInAgreement>(_PartyRelInAgreement_QNAME, PartyRelInAgreement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "Group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyAlternateIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyAlternateIdentifier")
    public JAXBElement<PartyAlternateIdentifier> createPartyAlternateIdentifier(PartyAlternateIdentifier value) {
        return new JAXBElement<PartyAlternateIdentifier>(_PartyAlternateIdentifier_QNAME, PartyAlternateIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyAlternateName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyAlternateName")
    public JAXBElement<PartyAlternateName> createPartyAlternateName(PartyAlternateName value) {
        return new JAXBElement<PartyAlternateName>(_PartyAlternateName_QNAME, PartyAlternateName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "OrganizationDetail")
    public JAXBElement<OrganizationDetail> createOrganizationDetail(OrganizationDetail value) {
        return new JAXBElement<OrganizationDetail>(_OrganizationDetail_QNAME, OrganizationDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgreementKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "AgreementKey")
    public JAXBElement<AgreementKey> createAgreementKey(AgreementKey value) {
        return new JAXBElement<AgreementKey>(_AgreementKey_QNAME, AgreementKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyPhone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyPhone")
    public JAXBElement<PartyPhone> createPartyPhone(PartyPhone value) {
        return new JAXBElement<PartyPhone>(_PartyPhone_QNAME, PartyPhone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyCore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyCore")
    public JAXBElement<PartyCore> createPartyCore(PartyCore value) {
        return new JAXBElement<PartyCore>(_PartyCore_QNAME, PartyCore.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyPreference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyPreference")
    public JAXBElement<PartyPreference> createPartyPreference(PartyPreference value) {
        return new JAXBElement<PartyPreference>(_PartyPreference_QNAME, PartyPreference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgreementRelationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "AgreementRelationship")
    public JAXBElement<AgreementRelationship> createAgreementRelationship(AgreementRelationship value) {
        return new JAXBElement<AgreementRelationship>(_AgreementRelationship_QNAME, AgreementRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "AbstractFault")
    public JAXBElement<AbstractFault> createAbstractFault(AbstractFault value) {
        return new JAXBElement<AbstractFault>(_AbstractFault_QNAME, AbstractFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyRoleInAgreement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyRoleInAgreement")
    public JAXBElement<PartyRoleInAgreement> createPartyRoleInAgreement(PartyRoleInAgreement value) {
        return new JAXBElement<PartyRoleInAgreement>(_PartyRoleInAgreement_QNAME, PartyRoleInAgreement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyAddress")
    public JAXBElement<PartyAddress> createPartyAddress(PartyAddress value) {
        return new JAXBElement<PartyAddress>(_PartyAddress_QNAME, PartyAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PersonDetail")
    public JAXBElement<PersonDetail> createPersonDetail(PersonDetail value) {
        return new JAXBElement<PersonDetail>(_PersonDetail_QNAME, PersonDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyCitizenship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyCitizenship")
    public JAXBElement<PartyCitizenship> createPartyCitizenship(PartyCitizenship value) {
        return new JAXBElement<PartyCitizenship>(_PartyCitizenship_QNAME, PartyCitizenship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyElectronicAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "services.gpm.metlife.com/PartyData", name = "PartyElectronicAddress")
    public JAXBElement<PartyElectronicAddress> createPartyElectronicAddress(PartyElectronicAddress value) {
        return new JAXBElement<PartyElectronicAddress>(_PartyElectronicAddress_QNAME, PartyElectronicAddress.class, null, value);
    }

}
