//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 04:03:14 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "services.gpm.metlife.com/PartyData", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.metlife.gpm.services.partydata;
