//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 04:03:14 PM EDT 
//


package com.metlife.gpm.services.partydata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyCore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyCore">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Party" type="{services.gpm.metlife.com/PartyData}Party"/>
 *         &lt;element name="Address" type="{services.gpm.metlife.com/PartyData}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyPhone" type="{services.gpm.metlife.com/PartyData}PartyPhone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyElectronicAddress" type="{services.gpm.metlife.com/PartyData}PartyElectronicAddress" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyCore", propOrder = {
    "party",
    "address",
    "partyPhone",
    "partyElectronicAddress"
})
public class PartyCore {

    @XmlElement(name = "Party", required = true)
    protected Party party;
    @XmlElement(name = "Address")
    protected List<Address> address;
    @XmlElement(name = "PartyPhone")
    protected List<PartyPhone> partyPhone;
    @XmlElement(name = "PartyElectronicAddress")
    protected List<PartyElectronicAddress> partyElectronicAddress;

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link Party }
     *     
     */
    public Party getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link Party }
     *     
     */
    public void setParty(Party value) {
        this.party = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the partyPhone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyPhone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyPhone }
     * 
     * 
     */
    public List<PartyPhone> getPartyPhone() {
        if (partyPhone == null) {
            partyPhone = new ArrayList<PartyPhone>();
        }
        return this.partyPhone;
    }

    /**
     * Gets the value of the partyElectronicAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyElectronicAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyElectronicAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyElectronicAddress }
     * 
     * 
     */
    public List<PartyElectronicAddress> getPartyElectronicAddress() {
        if (partyElectronicAddress == null) {
            partyElectronicAddress = new ArrayList<PartyElectronicAddress>();
        }
        return this.partyElectronicAddress;
    }

}
