//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 04:03:14 PM EDT 
//


package com.metlife.gpm.services.partydata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyLogical complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyLogical">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{services.gpm.metlife.com/PartyData}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Agreement" type="{services.gpm.metlife.com/PartyData}Agreement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AgreementKey" type="{services.gpm.metlife.com/PartyData}AgreementKey" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AgreementRelationship" type="{services.gpm.metlife.com/PartyData}AgreementRelationship" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Group" type="{services.gpm.metlife.com/PartyData}Group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrganizationDetail" type="{services.gpm.metlife.com/PartyData}OrganizationDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Party" type="{services.gpm.metlife.com/PartyData}Party"/>
 *         &lt;element name="PartyAddress" type="{services.gpm.metlife.com/PartyData}PartyAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyAlternateIdentifier" type="{services.gpm.metlife.com/PartyData}PartyAlternateIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyAlternateName" type="{services.gpm.metlife.com/PartyData}PartyAlternateName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyCitizenship" type="{services.gpm.metlife.com/PartyData}PartyCitizenship" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyElectronicAddress" type="{services.gpm.metlife.com/PartyData}PartyElectronicAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyGroup" type="{services.gpm.metlife.com/PartyData}PartyGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonDetail" type="{services.gpm.metlife.com/PartyData}PersonDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyPhone" type="{services.gpm.metlife.com/PartyData}PartyPhone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyPreference" type="{services.gpm.metlife.com/PartyData}PartyPreference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyRelInAgreement" type="{services.gpm.metlife.com/PartyData}PartyRelInAgreement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyRelationship" type="{services.gpm.metlife.com/PartyData}PartyRelationship" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyRestriction" type="{services.gpm.metlife.com/PartyData}PartyRestriction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyRoleInAgreement" type="{services.gpm.metlife.com/PartyData}PartyRoleInAgreement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyLogical", propOrder = {
    "address",
    "agreement",
    "agreementKey",
    "agreementRelationship",
    "group",
    "organizationDetail",
    "party",
    "partyAddress",
    "partyAlternateIdentifier",
    "partyAlternateName",
    "partyCitizenship",
    "partyElectronicAddress",
    "partyGroup",
    "personDetail",
    "partyPhone",
    "partyPreference",
    "partyRelInAgreement",
    "partyRelationship",
    "partyRestriction",
    "partyRoleInAgreement"
})
public class PartyLogical {

    @XmlElement(name = "Address")
    protected List<Address> address;
    @XmlElement(name = "Agreement")
    protected List<Agreement> agreement;
    @XmlElement(name = "AgreementKey")
    protected List<AgreementKey> agreementKey;
    @XmlElement(name = "AgreementRelationship")
    protected List<AgreementRelationship> agreementRelationship;
    @XmlElement(name = "Group")
    protected List<Group> group;
    @XmlElement(name = "OrganizationDetail")
    protected List<OrganizationDetail> organizationDetail;
    @XmlElement(name = "Party", required = true)
    protected Party party;
    @XmlElement(name = "PartyAddress")
    protected List<PartyAddress> partyAddress;
    @XmlElement(name = "PartyAlternateIdentifier")
    protected List<PartyAlternateIdentifier> partyAlternateIdentifier;
    @XmlElement(name = "PartyAlternateName")
    protected List<PartyAlternateName> partyAlternateName;
    @XmlElement(name = "PartyCitizenship")
    protected List<PartyCitizenship> partyCitizenship;
    @XmlElement(name = "PartyElectronicAddress")
    protected List<PartyElectronicAddress> partyElectronicAddress;
    @XmlElement(name = "PartyGroup")
    protected List<PartyGroup> partyGroup;
    @XmlElement(name = "PersonDetail")
    protected List<PersonDetail> personDetail;
    @XmlElement(name = "PartyPhone")
    protected List<PartyPhone> partyPhone;
    @XmlElement(name = "PartyPreference")
    protected List<PartyPreference> partyPreference;
    @XmlElement(name = "PartyRelInAgreement")
    protected List<PartyRelInAgreement> partyRelInAgreement;
    @XmlElement(name = "PartyRelationship")
    protected List<PartyRelationship> partyRelationship;
    @XmlElement(name = "PartyRestriction")
    protected List<PartyRestriction> partyRestriction;
    @XmlElement(name = "PartyRoleInAgreement")
    protected List<PartyRoleInAgreement> partyRoleInAgreement;

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgreement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Agreement }
     * 
     * 
     */
    public List<Agreement> getAgreement() {
        if (agreement == null) {
            agreement = new ArrayList<Agreement>();
        }
        return this.agreement;
    }

    /**
     * Gets the value of the agreementKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreementKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgreementKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgreementKey }
     * 
     * 
     */
    public List<AgreementKey> getAgreementKey() {
        if (agreementKey == null) {
            agreementKey = new ArrayList<AgreementKey>();
        }
        return this.agreementKey;
    }

    /**
     * Gets the value of the agreementRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreementRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgreementRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgreementRelationship }
     * 
     * 
     */
    public List<AgreementRelationship> getAgreementRelationship() {
        if (agreementRelationship == null) {
            agreementRelationship = new ArrayList<AgreementRelationship>();
        }
        return this.agreementRelationship;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     * 
     * 
     */
    public List<Group> getGroup() {
        if (group == null) {
            group = new ArrayList<Group>();
        }
        return this.group;
    }

    /**
     * Gets the value of the organizationDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationDetail }
     * 
     * 
     */
    public List<OrganizationDetail> getOrganizationDetail() {
        if (organizationDetail == null) {
            organizationDetail = new ArrayList<OrganizationDetail>();
        }
        return this.organizationDetail;
    }

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link Party }
     *     
     */
    public Party getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link Party }
     *     
     */
    public void setParty(Party value) {
        this.party = value;
    }

    /**
     * Gets the value of the partyAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyAddress }
     * 
     * 
     */
    public List<PartyAddress> getPartyAddress() {
        if (partyAddress == null) {
            partyAddress = new ArrayList<PartyAddress>();
        }
        return this.partyAddress;
    }

    /**
     * Gets the value of the partyAlternateIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyAlternateIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyAlternateIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyAlternateIdentifier }
     * 
     * 
     */
    public List<PartyAlternateIdentifier> getPartyAlternateIdentifier() {
        if (partyAlternateIdentifier == null) {
            partyAlternateIdentifier = new ArrayList<PartyAlternateIdentifier>();
        }
        return this.partyAlternateIdentifier;
    }

    /**
     * Gets the value of the partyAlternateName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyAlternateName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyAlternateName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyAlternateName }
     * 
     * 
     */
    public List<PartyAlternateName> getPartyAlternateName() {
        if (partyAlternateName == null) {
            partyAlternateName = new ArrayList<PartyAlternateName>();
        }
        return this.partyAlternateName;
    }

    /**
     * Gets the value of the partyCitizenship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyCitizenship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyCitizenship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyCitizenship }
     * 
     * 
     */
    public List<PartyCitizenship> getPartyCitizenship() {
        if (partyCitizenship == null) {
            partyCitizenship = new ArrayList<PartyCitizenship>();
        }
        return this.partyCitizenship;
    }

    /**
     * Gets the value of the partyElectronicAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyElectronicAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyElectronicAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyElectronicAddress }
     * 
     * 
     */
    public List<PartyElectronicAddress> getPartyElectronicAddress() {
        if (partyElectronicAddress == null) {
            partyElectronicAddress = new ArrayList<PartyElectronicAddress>();
        }
        return this.partyElectronicAddress;
    }

    /**
     * Gets the value of the partyGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyGroup }
     * 
     * 
     */
    public List<PartyGroup> getPartyGroup() {
        if (partyGroup == null) {
            partyGroup = new ArrayList<PartyGroup>();
        }
        return this.partyGroup;
    }

    /**
     * Gets the value of the personDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonDetail }
     * 
     * 
     */
    public List<PersonDetail> getPersonDetail() {
        if (personDetail == null) {
            personDetail = new ArrayList<PersonDetail>();
        }
        return this.personDetail;
    }

    /**
     * Gets the value of the partyPhone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyPhone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyPhone }
     * 
     * 
     */
    public List<PartyPhone> getPartyPhone() {
        if (partyPhone == null) {
            partyPhone = new ArrayList<PartyPhone>();
        }
        return this.partyPhone;
    }

    /**
     * Gets the value of the partyPreference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyPreference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyPreference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyPreference }
     * 
     * 
     */
    public List<PartyPreference> getPartyPreference() {
        if (partyPreference == null) {
            partyPreference = new ArrayList<PartyPreference>();
        }
        return this.partyPreference;
    }

    /**
     * Gets the value of the partyRelInAgreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyRelInAgreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyRelInAgreement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRelInAgreement }
     * 
     * 
     */
    public List<PartyRelInAgreement> getPartyRelInAgreement() {
        if (partyRelInAgreement == null) {
            partyRelInAgreement = new ArrayList<PartyRelInAgreement>();
        }
        return this.partyRelInAgreement;
    }

    /**
     * Gets the value of the partyRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRelationship }
     * 
     * 
     */
    public List<PartyRelationship> getPartyRelationship() {
        if (partyRelationship == null) {
            partyRelationship = new ArrayList<PartyRelationship>();
        }
        return this.partyRelationship;
    }

    /**
     * Gets the value of the partyRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRestriction }
     * 
     * 
     */
    public List<PartyRestriction> getPartyRestriction() {
        if (partyRestriction == null) {
            partyRestriction = new ArrayList<PartyRestriction>();
        }
        return this.partyRestriction;
    }

    /**
     * Gets the value of the partyRoleInAgreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyRoleInAgreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyRoleInAgreement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRoleInAgreement }
     * 
     * 
     */
    public List<PartyRoleInAgreement> getPartyRoleInAgreement() {
        if (partyRoleInAgreement == null) {
            partyRoleInAgreement = new ArrayList<PartyRoleInAgreement>();
        }
        return this.partyRoleInAgreement;
    }

}
