
package com.informatica.dis.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WS_GPM_ODSPortType", targetNamespace = "http://www.informatica.com/dis/ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSGPMODSPortType {


    /**
     * 
     * @param rowidOBJECT
     * @return
     *     returns com.informatica.dis.ws.GetODSDetailsByPartyRowidObjectResponse.Party
     */
    @WebMethod(operationName = "Get_ODSDetails_by_Party_Rowid_Object")
    @WebResult(name = "Party", targetNamespace = "http://www.informatica.com/dis/ws/")
    @RequestWrapper(localName = "Get_ODSDetails_by_Party_Rowid_Object", targetNamespace = "http://www.informatica.com/dis/ws/", className = "com.informatica.dis.ws.GetODSDetailsByPartyRowidObject")
    @ResponseWrapper(localName = "Get_ODSDetails_by_Party_Rowid_ObjectResponse", targetNamespace = "http://www.informatica.com/dis/ws/", className = "com.informatica.dis.ws.GetODSDetailsByPartyRowidObjectResponse")
    public com.informatica.dis.ws.GetODSDetailsByPartyRowidObjectResponse.Party getODSDetailsByPartyRowidObject(
        @WebParam(name = "ROWID_OBJECT", targetNamespace = "http://www.informatica.com/dis/ws/")
        String rowidOBJECT);

    /**
     * 
     * @param rowidOBJECT
     * @param agmtID
     * @return
     *     returns com.informatica.dis.ws.GetODSDetailsByPartyAgreementResponse.Party
     */
    @WebMethod(operationName = "Get_ODSDetails_by_Party_Agreement")
    @WebResult(name = "Party", targetNamespace = "http://www.informatica.com/dis/ws/")
    @RequestWrapper(localName = "Get_ODSDetails_by_Party_Agreement", targetNamespace = "http://www.informatica.com/dis/ws/", className = "com.informatica.dis.ws.GetODSDetailsByPartyAgreement")
    @ResponseWrapper(localName = "Get_ODSDetails_by_Party_AgreementResponse", targetNamespace = "http://www.informatica.com/dis/ws/", className = "com.informatica.dis.ws.GetODSDetailsByPartyAgreementResponse")
    public com.informatica.dis.ws.GetODSDetailsByPartyAgreementResponse.Party getODSDetailsByPartyAgreement(
        @WebParam(name = "ROWID_OBJECT", targetNamespace = "http://www.informatica.com/dis/ws/")
        String rowidOBJECT,
        @WebParam(name = "AGMT_ID", targetNamespace = "http://www.informatica.com/dis/ws/")
        String agmtID);

}
