//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 04:03:14 PM EDT 
//


package com.metlife.gpm.services.partymessages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.metlife.gpm.services.partydata.ConsumerId;
import com.metlife.gpm.services.partydata.PartySearchCriteria;


/**
 * <p>Java class for PartySearchRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartySearchRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsumerId" type="{services.gpm.metlife.com/PartyData}ConsumerId"/>
 *         &lt;element name="PartySearchCriteria" type="{services.gpm.metlife.com/PartyData}PartySearchCriteria"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartySearchRequest", propOrder = {
    "consumerId",
    "partySearchCriteria"
})
@XmlRootElement(name = "PartySearchRequest")
public class PartySearchRequest {

    @XmlElement(name = "ConsumerId", required = true)
    protected ConsumerId consumerId;
    @XmlElement(name = "PartySearchCriteria", required = true)
    protected PartySearchCriteria partySearchCriteria;

    /**
     * Gets the value of the consumerId property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerId }
     *     
     */
    public ConsumerId getConsumerId() {
        return consumerId;
    }

    /**
     * Sets the value of the consumerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerId }
     *     
     */
    public void setConsumerId(ConsumerId value) {
        this.consumerId = value;
    }

    /**
     * Gets the value of the partySearchCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link PartySearchCriteria }
     *     
     */
    public PartySearchCriteria getPartySearchCriteria() {
        return partySearchCriteria;
    }

    /**
     * Sets the value of the partySearchCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartySearchCriteria }
     *     
     */
    public void setPartySearchCriteria(PartySearchCriteria value) {
        this.partySearchCriteria = value;
    }

}
