
package com.metlife.gpm.services.partyservice;

import javax.xml.ws.WebFault;
import com.metlife.gpm.services.partydata.BusinessFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BusinessFault", targetNamespace = "services.gpm.metlife.com/PartyData")
public class BusinessFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BusinessFaultMessage(String message, BusinessFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BusinessFaultMessage(String message, BusinessFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.metlife.gpm.services.partydata.BusinessFault
     */
    public BusinessFault getFaultInfo() {
        return faultInfo;
    }

}
